### ISSUE TITLE
eu.gcr.io/kyma-project/test-infra/buildpack-java is not maintained anymore.

### ISSUE THREAD

**Issue by dekiel** [kyma-incubator/ord-service#57]
We will not maintain eu.gcr.io/kyma-project/test-infra/buildpack-java image in test-infra repository. All files related to this image where removed from kyma-project/test-infra directory. Pleas align your makefile https://github.com/kyma-incubator/ord-service/blob/3c5d286ca612397de625eb8039330087683cf727/components/ord-service/Makefile#L3

**Comment by KirilKabakchiev** [comment]
Thanks for letting us know. Please keep the image while we ensure we have properly adapted our makefiles. We will let you know when we are ready so that you can proceed with the removal

**Comment by tobiscr** [comment]
Obsolete, can stay closed
